services:
  backend:
    build: ./backend
    image: spm-backend:latest
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgresql://${RDS_USER}:${RDS_PASSWORD}@${RDS_HOST}:${RDS_PORT}/${POSTGRES_DB}
    restart: always

  frontend:
    build: ./app
    image: spm-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always