services:
  backend:
    build: ./backend
    image: spm-backend:latest
    env_file:
      - .env.prod
    restart: always

  frontend:
    build: ./app
    image: spm-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always